apiVersion: v1
kind: ConfigMap
data:
  oidc.config: |
    name: Keycloak
    issuer: https://localhost:8080
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "family_name", "given_name", "groups", "preferred_username"]
  url: https://localhost:8081
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd



