apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  controller.log.level: "debug"
  server.log.level: "debug"
  server.oidc.cache.expiration: "10m0s"
  reposerver.log.level: "debug"