apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- install.yaml
- ingress.yaml
- argocd-secret.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml
- argocd-ssh-known-hosts-cm.yaml
